spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://111.111.111.111:3306/teachcrm?useUnicode=true&characterEncoding=utf-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5

mybatis:
  type-aliases-package: com.didoumi.www.data.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /crm
